# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=100)),
                ('post_text', models.TextField(default=b'')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('time', models.DateField(auto_now_add=True)),
                ('up_vote', models.IntegerField(default=0)),
                ('category', models.TextField(default=b'')),
                ('submitter', models.TextField(default=b'')),
            ],
            options={
                'get_latest_by': 'time',
            },
        ),
    ]
