# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='authen.Account'),
        ),
    ]
