# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('new_post', '0003_auto_20160126_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'', max_length=200)),
                ('shown_username', models.TextField(default=b'', max_length=20)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='new_post.Post')),
            ],
        ),
    ]
